version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: userpassword
      MYSQL_USER: user
      MYSQL_DATABASE: api_development
      MYSQL_PASSWORD: userpassword
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    # MySQL8.0からセキュリティが強化されたようで、--default-authentication-plugin=mysql_native_password を実行して認証方式を mysql_native_password へ変更する必要があり
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      RAILS_DB_HOST: db # データベースコンテナ名と一致させる
      RAILS_DB_NAME: api_development # MYSQL_DATABASEと一致させる
      RAILS_DB_USER: user # MYSQL_USERと一致させる
      RAILS_DB_PASSWORD: userpassword # MYSQL_PASSWORDと一致させる
      RAILS_ENV: development
      RAILS_HOST_URL: http://localhost:3000
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      NEXT_PUBLIC_API_SERVER_HOST:
    command: yarn dev
