User.create(name: '小島仁', grade: 1)
teacher1 = Teacher.create(name: '山田太郎')
subject1 = Subject.create(title: '統計基礎', weekday: 'friday', period: 3, teacher_id: teacher1.id)
Lecture.create(title: 'ガイダンス', date: Date.parse('2020-04-23'), subject_id: subject1.id)
Lecture.create(title: '確率変数と確率分布', date: Date.parse('2020-04-30'), subject_id: subject1.id)
teacher2 = Teacher.create(name: '島田小次郎')
subject2 = Subject.create(title: '統計基礎', weekday: 'sunday', period: 2, teacher_id: teacher2.id)
Lecture.create(title: 'オリエンテーリング', date: Date.parse('2020-05-23'), subject_id: subject2.id)
Lecture.create(title: '微分積分', date: Date.parse('2020-05-29'), subject_id: subject2.id)
